services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=sentinel
      - POSTGRES_PASSWORD=sentinel_pass
      - POSTGRES_DB=sentinel_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      - MEILI_MASTER_KEY=sentinel_master_key
    ports:
      - '7700:7700'
    volumes:
      - meili_data:/meili_data

volumes:
  postgres_data:
  redis_data:
  meili_data:
